version: 2.1
orbs:
  node: circleci/node@5.0.3

jobs:
  release:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn semantic-release --debug

workflows:
  test_and_release:
    jobs:
      - node/run:
          name: lint
          pkg-manager: yarn
          yarn-run: lint
      - node/test:
          pkg-manager: yarn
          matrix:
            parameters:
              version:
                - "18.12"
                - "16.18"
                - "14.21"
      - release:
          requires:
            - node/test
            - lint
